import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { renderDirectory } from '@nci-gis/js-tmpl';

import { ENFORCEMENT_FILES } from '../constants.js';
import { resolveScaffoldConfig } from './index.js';
import {
  hasManagedRegion,
  mergeManagedRegion,
  adoptManagedRegion,
} from './managed-region.js';

/**
 * Bring the generated surface up to date without destroying anything.
 *
 * The full scaffold has one behaviour for every file, so refreshing a stub
 * meant `--force`, and `--force` also replaces `.agents/` wholesale. In a repo
 * with real curated canon that trade is never worth making, which left no way
 * to pick up template changes at all.
 *
 * Sync separates the two kinds of generated file:
 *
 * - **Managed** — the template owns a fenced region (the harness stubs). Only
 *   the region is replaced, so author content cannot be lost.
 * - **Seeded** — written once and then the human's (all of `.agents/`).
 *   Created when absent, never touched when present.
 *
 * Nothing here can lose work, so there is no `--force` and no conflict list.
 * Files it will not touch are reported instead, so the human can decide.
 *
 * @param {object} options
 * @param {string} options.templateName
 * @param {string} options.outputDir
 * @param {object} [options.overrides]
 * @param {boolean} [options.adopt] - Bring an unmanaged stub under management
 *   by inserting the region. Off by default: a stub generated by an older
 *   version already contains a copy of the block, and adoption would duplicate
 *   it rather than replace it.
 * @param {boolean} [options.dryRun] - Report without writing.
 * @returns {Promise<{ created: string[], updated: string[], unchanged: string[],
 *   adopted: string[], unmanaged: string[], drifted: string[] }>}
 */
export async function sync({
  templateName,
  outputDir,
  overrides = {},
  adopt = false,
  dryRun = false,
}) {
  const { config } = resolveScaffoldConfig({
    templateName,
    outputDir,
    overrides,
  });
  const outDir = config.outDir;

  const stagingDir = fs.mkdtempSync(path.join(os.tmpdir(), 'a2scaffold-sync-'));
  try {
    config.outDir = stagingDir;
    await renderDirectory(config);

    /** @type {Record<string, string[]>} */
    const result = {
      created: [],
      updated: [],
      unchanged: [],
      adopted: [],
      unmanaged: [],
      drifted: [],
    };

    /** @param {string} rel */
    const walk = (rel) => {
      const abs = path.join(stagingDir, rel);
      if (fs.statSync(abs).isDirectory()) {
        for (const name of fs.readdirSync(abs)) {
          walk(rel ? path.join(rel, name) : name);
        }
        return;
      }

      const dest = path.join(outDir, rel);
      const incoming = fs.readFileSync(abs, 'utf8');

      // Absent: creating a file cannot destroy one. This is how an existing
      // repo picks up genuinely new template files without a re-scaffold.
      if (!fs.existsSync(dest)) {
        if (!dryRun) {
          fs.mkdirSync(path.dirname(dest), { recursive: true });
          fs.writeFileSync(dest, incoming);
        }
        result.created.push(rel);
        return;
      }

      const existing = fs.readFileSync(dest, 'utf8');

      if (hasManagedRegion(incoming)) {
        const merged = mergeManagedRegion(existing, incoming);
        if (merged !== null) {
          if (merged === existing) {
            result.unchanged.push(rel);
          } else {
            if (!dryRun) fs.writeFileSync(dest, merged);
            result.updated.push(rel);
          }
          return;
        }

        // The template owns a region here but the file has none.
        if (adopt) {
          const wrapped = adoptManagedRegion(existing, incoming);
          if (wrapped !== null) {
            if (!dryRun) fs.writeFileSync(dest, wrapped);
            result.adopted.push(rel);
            return;
          }
        }
        result.unmanaged.push(rel);
        return;
      }

      // Enforcement files are seeded, but falling behind them has a security
      // cost a stale doc does not: a new `ask` rule protecting a new directory
      // should reach existing repos. Report, never overwrite.
      if (ENFORCEMENT_FILES.includes(rel.split(path.sep).join('/'))) {
        if (existing !== incoming) result.drifted.push(rel);
        return;
      }

      // Seeded and present: the human's. Silent on purpose — our own
      // philosophy.md is three times the template's, and reporting that every
      // run would train people to ignore the output.
    };

    walk('');
    return /** @type {any} */ (result);
  } finally {
    fs.rmSync(stagingDir, { recursive: true, force: true });
  }
}
