import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

import {
  validateSkill,
  scoreConformance,
  auditSkill,
  listSkills,
  parseSkillSource,
  installSkill,
  isSkillRef,
  discoverSkills,
  installSkillRef,
} from '../src/skills/index.js';
import yaml from 'js-yaml';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES = path.join(__dirname, 'fixtures');

// ── validateSkill ───────────────────────────────────────────────────

describe('validateSkill', () => {
  it('accepts a valid skill', () => {
    const result = validateSkill(path.join(FIXTURES, 'valid-skill'));
    assert.equal(result.valid, true);
    assert.equal(result.errors.length, 0);
    assert.equal(result.skill.name, 'valid-skill');
    assert.ok(result.skill.description.length > 0);
  });

  it('rejects when SKILL.md is missing', () => {
    const result = validateSkill(path.join(FIXTURES, 'base-output'));
    assert.equal(result.valid, false);
    assert.ok(result.errors.some((e) => e.includes('SKILL.md not found')));
  });

  it('rejects when frontmatter is missing', () => {
    const result = validateSkill(path.join(FIXTURES, 'no-frontmatter-skill'));
    assert.equal(result.valid, false);
    assert.ok(result.errors.some((e) => e.includes('no YAML frontmatter')));
  });

  it('rejects invalid name (uppercase, empty description)', () => {
    const result = validateSkill(path.join(FIXTURES, 'invalid-skill'));
    assert.equal(result.valid, false);
    assert.ok(result.errors.some((e) => e.includes('lowercase alphanumeric')));
    assert.ok(result.errors.some((e) => e.includes('description')));
  });

  it('rejects name that does not match directory name', () => {
    // valid-skill has name: "valid-skill" — check from a renamed dir
    const tmpDir = path.join(FIXTURES, '_tmp-mismatch-skill');
    fs.mkdirSync(tmpDir, { recursive: true });
    fs.writeFileSync(
      path.join(tmpDir, 'SKILL.md'),
      '---\nname: other-name\ndescription: Test.\n---\n'
    );

    try {
      const result = validateSkill(tmpDir);
      assert.equal(result.valid, false);
      assert.ok(
        result.errors.some((e) => e.includes('does not match directory'))
      );
    } finally {
      fs.rmSync(tmpDir, { recursive: true });
    }
  });

  it('rejects name with consecutive hyphens', () => {
    const tmpDir = path.join(FIXTURES, '_tmp-bad--name');
    fs.mkdirSync(tmpDir, { recursive: true });
    fs.writeFileSync(
      path.join(tmpDir, 'SKILL.md'),
      '---\nname: bad--name\ndescription: Test.\n---\n'
    );

    try {
      const result = validateSkill(tmpDir);
      assert.equal(result.valid, false);
      assert.ok(result.errors.some((e) => e.includes('consecutive hyphens')));
    } finally {
      fs.rmSync(tmpDir, { recursive: true });
    }
  });
});

// ── validateSkill — skill-ref chain ─────────────────────────────────

describe('validateSkill (skill-ref chain)', () => {
  /**
   * Helper: create a raw valid skill at <parent>/skills/<name>
   */
  function createRawSkill(parent, name) {
    const dir = path.join(parent, 'skills', name);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(
      path.join(dir, 'SKILL.md'),
      `---\nname: ${name}\ndescription: A real skill.\n---\n`
    );
    return dir;
  }

  /**
   * Helper: create a skill-ref at <parent>/skills/<name> pointing to target.
   * `rootPath` is the relative path from ref dir to a project root such
   * that `<rootPath>/<sourceDir>` resolves to the target skill.
   */
  function createRef(parent, name, rootPath, sourceDir) {
    const dir = path.join(parent, 'skills', name);
    fs.mkdirSync(dir, { recursive: true });
    const skillPath = `${rootPath}/${sourceDir}`;
    fs.writeFileSync(
      path.join(dir, 'SKILL.md'),
      `---\nname: ${name}\ndescription: A ref.\nmetadata:\n  type: skill-ref\n  rootPath: ${rootPath}\n  skillPath: ${skillPath}\n---\n\n<!-- Do not edit this file directly. -->\n`
    );
    return dir;
  }

  it('accepts a one-hop ref whose terminal is a valid raw skill', () => {
    const tmp = fs.mkdtempSync(path.join(FIXTURES, '_tmp-ref-chain-ok-'));
    try {
      const src = path.join(tmp, 'src-agents');
      const dst = path.join(tmp, 'dst-agents');
      createRawSkill(src, 'my-skill');
      // ref dir: tmp/dst-agents/skills/my-skill → rootPath 3 levels up to tmp
      createRef(dst, 'my-skill', '../../..', 'src-agents/skills/my-skill');

      const result = validateSkill(path.join(dst, 'skills', 'my-skill'));
      assert.equal(result.valid, true, result.errors.join('; '));
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });

  it('reports broken ref when target does not exist', () => {
    const tmp = fs.mkdtempSync(path.join(FIXTURES, '_tmp-ref-chain-broken-'));
    try {
      const dst = path.join(tmp, 'dst-agents');
      createRef(dst, 'ghost', '../../..', 'src-agents/skills/ghost');

      const result = validateSkill(path.join(dst, 'skills', 'ghost'));
      assert.equal(result.valid, false);
      assert.ok(
        result.errors.some((e) => e.includes('broken ref')),
        `expected broken-ref error, got: ${result.errors.join('; ')}`
      );
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });

  it('detects a ref cycle', () => {
    const tmp = fs.mkdtempSync(path.join(FIXTURES, '_tmp-ref-chain-cycle-'));
    try {
      const agentsA = path.join(tmp, 'agents-a');
      const agentsB = path.join(tmp, 'agents-b');
      // A → B → A
      createRef(agentsA, 'loop', '../../..', 'agents-b/skills/loop');
      createRef(agentsB, 'loop', '../../..', 'agents-a/skills/loop');

      const result = validateSkill(path.join(agentsA, 'skills', 'loop'));
      assert.equal(result.valid, false);
      assert.ok(
        result.errors.some((e) => e.includes('ref cycle')),
        `expected cycle error, got: ${result.errors.join('; ')}`
      );
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });

  it('bubbles terminal errors when the raw target is invalid', () => {
    const tmp = fs.mkdtempSync(path.join(FIXTURES, '_tmp-ref-chain-bad-term-'));
    try {
      const src = path.join(tmp, 'src-agents');
      const dst = path.join(tmp, 'dst-agents');
      // Terminal has no frontmatter (invalid)
      const terminalDir = path.join(src, 'skills', 'broken');
      fs.mkdirSync(terminalDir, { recursive: true });
      fs.writeFileSync(path.join(terminalDir, 'SKILL.md'), 'no frontmatter\n');

      createRef(dst, 'broken', '../../..', 'src-agents/skills/broken');

      const result = validateSkill(path.join(dst, 'skills', 'broken'));
      assert.equal(result.valid, false);
      assert.ok(
        result.errors.some((e) => e.includes('terminal skill invalid')),
        `expected bubbled error, got: ${result.errors.join('; ')}`
      );
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });
});

// ── listSkills ──────────────────────────────────────────────────────

describe('listSkills', () => {
  it('lists skills from a directory', () => {
    // Create a temporary agents dir with one skill
    const tmpAgents = path.join(FIXTURES, '_tmp-agents');
    const skillDir = path.join(tmpAgents, 'skills', 'test-skill');
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(
      path.join(skillDir, 'SKILL.md'),
      '---\nname: test-skill\ndescription: A test.\n---\n'
    );

    try {
      const skills = listSkills(tmpAgents);
      assert.equal(skills.length, 1);
      assert.equal(skills[0].name, 'test-skill');
      assert.equal(skills[0].description, 'A test.');
    } finally {
      fs.rmSync(tmpAgents, { recursive: true });
    }
  });

  it('returns empty array for empty skills directory', () => {
    const tmpAgents = path.join(FIXTURES, '_tmp-agents-empty');
    fs.mkdirSync(path.join(tmpAgents, 'skills'), { recursive: true });

    try {
      const skills = listSkills(tmpAgents);
      assert.equal(skills.length, 0);
    } finally {
      fs.rmSync(tmpAgents, { recursive: true });
    }
  });

  it('returns empty array when skills directory does not exist', () => {
    const skills = listSkills('/tmp/nonexistent-agents-dir');
    assert.equal(skills.length, 0);
  });

  it('skips directories without SKILL.md', () => {
    const tmpAgents = path.join(FIXTURES, '_tmp-agents-skip');
    fs.mkdirSync(path.join(tmpAgents, 'skills', 'no-skill'), {
      recursive: true,
    });

    try {
      const skills = listSkills(tmpAgents);
      assert.equal(skills.length, 0);
    } finally {
      fs.rmSync(tmpAgents, { recursive: true });
    }
  });
});

// ── parseSkillSource ────────────────────────────────────────────────

describe('parseSkillSource', () => {
  it('parses relative local path', () => {
    const result = parseSkillSource('./my-skill');
    assert.equal(result.type, 'local');
    assert.ok(result.localPath.endsWith('my-skill'));
  });

  it('parses parent-relative local path', () => {
    const result = parseSkillSource('../my-skill');
    assert.equal(result.type, 'local');
    assert.ok(result.localPath.includes('my-skill'));
  });

  it('parses absolute local path', () => {
    const result = parseSkillSource('/tmp/my-skill');
    assert.equal(result.type, 'local');
    assert.equal(result.localPath, '/tmp/my-skill');
  });

  it('parses GitHub shorthand (owner/repo)', () => {
    const result = parseSkillSource('anthropics/skills');
    assert.equal(result.type, 'github');
    assert.equal(result.owner, 'anthropics');
    assert.equal(result.repo, 'skills');
    assert.equal(result.skillPath, '');
  });

  it('parses GitHub shorthand with subpath', () => {
    const result = parseSkillSource('anthropics/skills/code-review');
    assert.equal(result.type, 'github');
    assert.equal(result.owner, 'anthropics');
    assert.equal(result.repo, 'skills');
    assert.equal(result.skillPath, 'code-review');
  });

  it('parses GitHub URL with tree/ref/path', () => {
    const result = parseSkillSource(
      'https://github.com/anthropics/skills/tree/main/code-review'
    );
    assert.equal(result.type, 'github');
    assert.equal(result.owner, 'anthropics');
    assert.equal(result.repo, 'skills');
    assert.equal(result.ref, 'main');
    assert.equal(result.skillPath, 'code-review');
  });

  it('throws for unparseable source', () => {
    assert.throws(() => parseSkillSource('just-a-word'), /Unable to parse/);
  });
});

// ── installSkill (local) ────────────────────────────────────────────

describe('installSkill (local)', () => {
  let tmpTarget;

  beforeEach(() => {
    tmpTarget = fs.mkdtempSync(path.join(FIXTURES, '_tmp-install-'));
  });

  afterEach(() => {
    fs.rmSync(tmpTarget, { recursive: true, force: true });
  });

  it('installs a valid skill from local path', () => {
    const source = path.join(FIXTURES, 'valid-skill');
    const result = installSkill(source, tmpTarget);

    assert.equal(result.name, 'valid-skill');
    assert.ok(fs.existsSync(path.join(tmpTarget, 'valid-skill', 'SKILL.md')));
  });

  it('fails when skill already exists without --force', () => {
    const source = path.join(FIXTURES, 'valid-skill');
    installSkill(source, tmpTarget);

    assert.throws(() => installSkill(source, tmpTarget), /already exists/);
  });

  it('overwrites with force option', () => {
    const source = path.join(FIXTURES, 'valid-skill');
    installSkill(source, tmpTarget);
    const result = installSkill(source, tmpTarget, { force: true });

    assert.equal(result.name, 'valid-skill');
    assert.ok(fs.existsSync(path.join(tmpTarget, 'valid-skill', 'SKILL.md')));
  });

  it('fails when source does not exist', () => {
    assert.throws(
      () => installSkill('/tmp/nonexistent-skill-path', tmpTarget),
      /does not exist/
    );
  });

  it('fails when source skill is invalid', () => {
    const source = path.join(FIXTURES, 'invalid-skill');
    assert.throws(
      () => installSkill(source, tmpTarget),
      /Source skill is invalid/
    );
  });
});

// ── isSkillRef ─────────────────────────────────────────────────────

describe('isSkillRef', () => {
  it('returns false for a regular skill', () => {
    const result = isSkillRef(path.join(FIXTURES, 'valid-skill'));
    assert.equal(result.isRef, false);
    assert.equal(result.content, null);
  });

  it('returns true for a skill-ref', () => {
    const result = isSkillRef(path.join(FIXTURES, 'skill-ref-skill'));
    assert.equal(result.isRef, true);
    assert.ok(result.content);
    assert.ok(result.content.includes('type: skill-ref'));
  });

  it('returns false when SKILL.md is missing', () => {
    const result = isSkillRef(path.join(FIXTURES, 'base-output'));
    assert.equal(result.isRef, false);
    assert.equal(result.content, null);
  });

  it('returns false when no frontmatter', () => {
    const result = isSkillRef(path.join(FIXTURES, 'no-frontmatter-skill'));
    assert.equal(result.isRef, false);
    assert.equal(result.content, null);
  });
});

// ── discoverSkills ─────────────────────────────────────────────────

describe('discoverSkills', () => {
  it('discovers skills in an agents directory', () => {
    const tmpAgents = path.join(FIXTURES, '_tmp-discover');
    const skillA = path.join(tmpAgents, 'skills', 'skill-a');
    const skillB = path.join(tmpAgents, 'skills', 'skill-b');
    fs.mkdirSync(skillA, { recursive: true });
    fs.mkdirSync(skillB, { recursive: true });
    fs.writeFileSync(
      path.join(skillA, 'SKILL.md'),
      '---\nname: skill-a\ndescription: A.\n---\n'
    );
    fs.writeFileSync(
      path.join(skillB, 'SKILL.md'),
      '---\nname: skill-b\ndescription: B.\n---\n'
    );

    try {
      const skills = discoverSkills(tmpAgents);
      assert.equal(skills.length, 2);
      assert.equal(skills[0].name, 'skill-a');
      assert.equal(skills[1].name, 'skill-b');
      assert.ok(skills[0].skillDir.endsWith('skill-a'));
    } finally {
      fs.rmSync(tmpAgents, { recursive: true });
    }
  });

  it('returns empty array when no skills directory', () => {
    const skills = discoverSkills('/tmp/nonexistent-agents');
    assert.equal(skills.length, 0);
  });

  it('returns empty array for empty skills directory', () => {
    const tmpAgents = path.join(FIXTURES, '_tmp-discover-empty');
    fs.mkdirSync(path.join(tmpAgents, 'skills'), { recursive: true });

    try {
      const skills = discoverSkills(tmpAgents);
      assert.equal(skills.length, 0);
    } finally {
      fs.rmSync(tmpAgents, { recursive: true });
    }
  });
});

// ── installSkillRef ────────────────────────────────────────────────

describe('installSkillRef', () => {
  let tmpFrom;
  let tmpTo;

  beforeEach(() => {
    tmpFrom = fs.mkdtempSync(path.join(FIXTURES, '_tmp-ref-from-'));
    tmpTo = fs.mkdtempSync(path.join(FIXTURES, '_tmp-ref-to-'));

    // Create a valid skill in the source agents dir
    const skillDir = path.join(tmpFrom, 'skills', 'test-skill');
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(
      path.join(skillDir, 'SKILL.md'),
      '---\nname: test-skill\ndescription: A test skill.\n---\n\n## Procedure\n1. Do it\n'
    );
  });

  afterEach(() => {
    fs.rmSync(tmpFrom, { recursive: true, force: true });
    fs.rmSync(tmpTo, { recursive: true, force: true });
  });

  it('creates a single skill ref', async () => {
    const results = await installSkillRef({
      from: tmpFrom,
      to: tmpTo,
      skill: 'test-skill',
    });

    assert.equal(results.length, 1);
    assert.equal(results[0].name, 'test-skill');

    const output = fs.readFileSync(
      path.join(tmpTo, 'skills', 'test-skill', 'SKILL.md'),
      'utf8'
    );
    assert.ok(output.includes('name: test-skill'));
    assert.ok(output.includes('type: skill-ref'));
    assert.ok(output.includes('rootPath:'));
    assert.ok(output.includes('skillPath:'));
  });

  it('creates refs for all skills with --skill all', async () => {
    // Add a second skill
    const skillDir = path.join(tmpFrom, 'skills', 'another-skill');
    fs.mkdirSync(skillDir, { recursive: true });
    fs.writeFileSync(
      path.join(skillDir, 'SKILL.md'),
      '---\nname: another-skill\ndescription: Another.\n---\n'
    );

    const results = await installSkillRef({
      from: tmpFrom,
      to: tmpTo,
      skill: 'all',
    });

    assert.equal(results.length, 2);
    const names = results.map((r) => r.name).sort((a, b) => a.localeCompare(b));
    assert.deepEqual(names, ['another-skill', 'test-skill']);
  });

  it('copies skill-ref source verbatim', async () => {
    // Replace source skill with a skill-ref
    const refDir = path.join(tmpFrom, 'skills', 'ref-skill');
    fs.mkdirSync(refDir, { recursive: true });
    const refContent =
      '---\nname: ref-skill\nmetadata:\n  type: skill-ref\n  rootPath: ../../..\n  skillPath: ../../../.agents/skills/ref-skill\n---\n\n<!-- Do not edit this file directly. -->\n';
    fs.writeFileSync(path.join(refDir, 'SKILL.md'), refContent);

    const results = await installSkillRef({
      from: tmpFrom,
      to: tmpTo,
      skill: 'ref-skill',
    });

    assert.equal(results.length, 1);
    const output = fs.readFileSync(
      path.join(tmpTo, 'skills', 'ref-skill', 'SKILL.md'),
      'utf8'
    );
    assert.equal(output, refContent);
  });

  it('errors when from === to', async () => {
    await assert.rejects(
      () =>
        installSkillRef({ from: tmpFrom, to: tmpFrom, skill: 'test-skill' }),
      /must differ/
    );
  });

  it('errors when dest has a real skill', async () => {
    // Create a real skill at dest
    const destSkill = path.join(tmpTo, 'skills', 'test-skill');
    fs.mkdirSync(destSkill, { recursive: true });
    fs.writeFileSync(
      path.join(destSkill, 'SKILL.md'),
      '---\nname: test-skill\ndescription: Real.\n---\n'
    );

    await assert.rejects(
      () =>
        installSkillRef({
          from: tmpFrom,
          to: tmpTo,
          skill: 'test-skill',
          force: true,
        }),
      /Cannot overwrite real skill/
    );
  });

  it('errors when dest has existing ref without --force', async () => {
    // First install
    await installSkillRef({ from: tmpFrom, to: tmpTo, skill: 'test-skill' });

    // Second install without force
    await assert.rejects(
      () => installSkillRef({ from: tmpFrom, to: tmpTo, skill: 'test-skill' }),
      /already exists/
    );
  });

  it('overwrites existing ref with --force', async () => {
    await installSkillRef({ from: tmpFrom, to: tmpTo, skill: 'test-skill' });

    const results = await installSkillRef({
      from: tmpFrom,
      to: tmpTo,
      skill: 'test-skill',
      force: true,
    });

    assert.equal(results.length, 1);
    assert.equal(results[0].name, 'test-skill');
  });

  it('errors when source skill does not exist', async () => {
    await assert.rejects(
      () => installSkillRef({ from: tmpFrom, to: tmpTo, skill: 'nonexistent' }),
      /not found/
    );
  });

  it('computes correct rootPath', async () => {
    await installSkillRef({ from: tmpFrom, to: tmpTo, skill: 'test-skill' });

    const output = fs.readFileSync(
      path.join(tmpTo, 'skills', 'test-skill', 'SKILL.md'),
      'utf8'
    );
    const match = output.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    const frontmatter = yaml.load(match[1]);

    // rootPath should be a relative path from dest skill dir to source parent
    const destSkillDir = path.join(tmpTo, 'skills', 'test-skill');
    const sourceRoot = path.resolve(tmpFrom, '..');
    const expected = path.relative(destSkillDir, sourceRoot);

    assert.equal(frontmatter.metadata.rootPath, expected);
  });

  it('creates a ref for a nested skill (path-style name)', async () => {
    // Add a nested skill: tmpFrom/skills/group/nested-skill/SKILL.md
    const nestedDir = path.join(tmpFrom, 'skills', 'group', 'nested-skill');
    fs.mkdirSync(nestedDir, { recursive: true });
    fs.writeFileSync(
      path.join(nestedDir, 'SKILL.md'),
      '---\nname: nested-skill\ndescription: Nested.\n---\n'
    );

    const results = await installSkillRef({
      from: tmpFrom,
      to: tmpTo,
      skill: 'group/nested-skill',
    });

    assert.equal(results.length, 1);
    assert.equal(results[0].name, 'group/nested-skill');

    const refFile = path.join(
      tmpTo,
      'skills',
      'group',
      'nested-skill',
      'SKILL.md'
    );
    assert.ok(fs.existsSync(refFile));
    const output = fs.readFileSync(refFile, 'utf8');
    // Frontmatter name uses the leaf segment so validation matches dir basename
    assert.ok(output.includes('name: nested-skill'));
    assert.ok(output.includes('type: skill-ref'));
  });

  it('discovers nested skills with --skill all', async () => {
    // Add a nested skill alongside the existing flat one
    const nestedDir = path.join(tmpFrom, 'skills', 'group', 'nested-skill');
    fs.mkdirSync(nestedDir, { recursive: true });
    fs.writeFileSync(
      path.join(nestedDir, 'SKILL.md'),
      '---\nname: nested-skill\ndescription: Nested.\n---\n'
    );

    const results = await installSkillRef({
      from: tmpFrom,
      to: tmpTo,
      skill: 'all',
    });

    const names = results.map((r) => r.name).sort((a, b) => a.localeCompare(b));
    assert.deepEqual(names, ['group/nested-skill', 'test-skill']);
  });

  it('errors when no skills found with --skill all', async () => {
    const emptyFrom = fs.mkdtempSync(path.join(FIXTURES, '_tmp-ref-empty-'));
    fs.mkdirSync(path.join(emptyFrom, 'skills'), { recursive: true });

    try {
      await assert.rejects(
        () => installSkillRef({ from: emptyFrom, to: tmpTo, skill: 'all' }),
        /No skills found/
      );
    } finally {
      fs.rmSync(emptyFrom, { recursive: true, force: true });
    }
  });
});

// ── scoreConformance ────────────────────────────────────────────────

describe('scoreConformance', () => {
  const GOOD_DESC =
    'Creates a new scaffold template from an existing directory tree. Use this ' +
    'when the user asks to add a template, promote a directory into templates/, ' +
    'or turn an example project into something reusable.';

  it('gives a well-formed skill full marks', () => {
    const r = scoreConformance(
      { name: 'demo', description: GOOD_DESC },
      '## Procedure\n\n1. Do the thing.'
    );
    assert.equal(r.score, 100);
    assert.deepEqual(r.warnings, []);
  });

  it('penalises a short description in proportion to the shortfall', () => {
    const near = scoreConformance(
      {
        name: 'demo',
        description: `${GOOD_DESC} extra`.split(' ').slice(0, 29).join(' '),
      },
      'body'
    );
    const far = scoreConformance(
      { name: 'demo', description: 'Use this when formatting.' },
      'body'
    );
    assert.ok(
      far.score < near.score,
      'a much shorter description must score lower'
    );
    assert.ok(near.score > 90, 'one word short should barely move the score');
  });

  it('flags a description that never says when to use the skill', () => {
    const r = scoreConformance(
      {
        name: 'demo',
        description:
          'A comprehensive utility that formats and rewrites project source files ' +
          'across many languages and configurations with assorted options provided.',
      },
      'body'
    );
    assert.ok(r.warnings.some((w) => w.code === 'description-no-trigger'));
  });

  it('flags an oversized body and an empty one', () => {
    const big = scoreConformance(
      { name: 'demo', description: GOOD_DESC },
      'x'.repeat(4 * 5001)
    );
    assert.ok(big.warnings.some((w) => w.code === 'body-over-budget'));

    const empty = scoreConformance(
      { name: 'demo', description: GOOD_DESC },
      '   '
    );
    assert.ok(empty.warnings.some((w) => w.code === 'body-empty'));
  });

  it('flags unrecognised frontmatter keys', () => {
    const r = scoreConformance(
      { name: 'demo', description: GOOD_DESC, 'when-to-use': 'typo' },
      'body'
    );
    assert.ok(
      r.warnings.some(
        (w) =>
          w.code === 'unknown-frontmatter-key' &&
          w.message.includes('when-to-use')
      )
    );
  });

  it('skips body and description checks for skill-refs', () => {
    const r = scoreConformance(
      { name: 'demo', description: 'A reference to a skill.' },
      '',
      { isRef: true }
    );
    assert.deepEqual(r.warnings, []);
    assert.equal(r.score, 100);
  });

  it('warns when description + when_to_use exceed the listing cap', () => {
    const r = scoreConformance(
      { name: 'demo', description: GOOD_DESC, when_to_use: 'y'.repeat(1537) },
      'body'
    );
    assert.ok(r.warnings.some((w) => w.code === 'listing-cap-exceeded'));
  });
});

// ── validateSkill exposes conformance ───────────────────────────────

describe('validateSkill (conformance)', () => {
  it('reports warnings and a score without affecting validity', () => {
    const result = validateSkill(path.join(FIXTURES, 'valid-skill'));
    assert.equal(result.valid, true);
    assert.ok(Array.isArray(result.warnings));
    assert.equal(typeof result.score, 'number');
  });
});

// ── auditSkill ──────────────────────────────────────────────────────

describe('auditSkill', () => {
  it('flags injection, credentials, network and execution in a hostile skill', () => {
    const { findings, clean } = auditSkill(
      path.join(FIXTURES, 'hostile-skill')
    );
    assert.equal(clean, false);
    const categories = new Set(findings.map((f) => f.category));
    for (const expected of [
      'injection',
      'credentials',
      'network',
      'execution',
    ]) {
      assert.ok(categories.has(expected), `missing ${expected} finding`);
    }
  });

  it('reports the file and line of each finding', () => {
    const { findings } = auditSkill(path.join(FIXTURES, 'hostile-skill'));
    const cred = findings.find((f) => f.category === 'credentials');
    assert.equal(cred.file, path.join('scripts', 'setup.sh'));
    assert.equal(typeof cred.line, 'number');
  });

  it('flags a skill that grants itself shell access', () => {
    const { findings } = auditSkill(path.join(FIXTURES, 'hostile-skill'));
    assert.ok(
      findings.some((f) => f.message.includes('allowed-tools')),
      'should flag Bash in allowed-tools'
    );
  });

  it('passes a benign skill', () => {
    const { clean, scanned } = auditSkill(path.join(FIXTURES, 'valid-skill'));
    assert.equal(clean, true);
    assert.ok(scanned > 0);
  });

  it('rejects a directory that is not a skill', () => {
    const { clean, findings } = auditSkill(FIXTURES);
    assert.equal(clean, false);
    assert.equal(findings[0].category, 'opaque');
  });
});

// ── auditSkill — calibration against real-world skills ──────────────
//
// Every finding below was a false positive found by running the audit over a
// production .agents/ that was not written with this tool in mind.

describe('auditSkill (false-positive calibration)', () => {
  const skill = () => auditSkill(path.join(FIXTURES, 'benign-tooling-skill'));

  it('does not flag a scoped Bash grant', () => {
    // `Bash(git log *)` is least privilege done right and must not score the
    // same as a bare `Bash`.
    const { findings } = skill();
    assert.ok(!findings.some((f) => f.message.includes('allowed-tools')));
  });

  it('flags an unscoped Bash grant', () => {
    const { findings } = auditSkill(path.join(FIXTURES, 'hostile-skill'));
    assert.ok(findings.some((f) => f.message.includes('allowed-tools')));
  });

  it('does not treat subprocess exception handling as execution', () => {
    // `except subprocess.CalledProcessError` is error handling.
    const { findings } = skill();
    const lines = findings
      .filter((f) => f.category === 'execution')
      .map((f) => f.line);
    assert.ok(!lines.includes(9), 'except clause must not be flagged');
  });

  it('still flags a real subprocess call', () => {
    const { findings } = skill();
    assert.ok(
      findings.some((f) => f.category === 'execution' && f.line === 7),
      'subprocess.check_output( is a genuine shell-out'
    );
  });

  it('does not treat urllib.parse as network access', () => {
    // urllib.parse is pure string handling; urllib.request is not.
    const { findings } = skill();
    assert.ok(!findings.some((f) => f.category === 'network'));
  });
});

// ── installSkill — artefact exclusion ───────────────────────────────

describe('installSkill (excludes build artefacts)', () => {
  it('does not copy caches, compiled files or node_modules', () => {
    const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'a2-junk-'));
    try {
      installSkill(path.join(FIXTURES, 'junk-skill'), tmp);
      const dest = path.join(tmp, 'junk-skill');

      // The skill itself arrives intact.
      assert.ok(fs.existsSync(path.join(dest, 'SKILL.md')));
      assert.ok(fs.existsSync(path.join(dest, 'scripts', 'fmt.py')));

      // Its working detritus does not.
      for (const junk of [
        'node_modules',
        path.join('scripts', '__pycache__'),
        path.join('scripts', 'fmt.pyc'),
      ]) {
        assert.ok(
          !fs.existsSync(path.join(dest, junk)),
          `${junk} should not be installed`
        );
      }
    } finally {
      fs.rmSync(tmp, { recursive: true, force: true });
    }
  });
});
